import { type NextPage } from "next";
import Head from "next/head";
import Input from "~/components/Input";

export const GeneratePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <form className="flex flex-col gap-4">
          <FormGroup>
            <label>Prompt</label>
            <Input placeholder="Enter your icon idea"></Input>
          </FormGroup>
          <button className="rounded-md bg-blue-400 px-4 py-2 hover:bg-blue-300">
            Generate
          </button>
        </form>
      </main>
    </>
  );
};
