import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import LogoCarousel from "~/components/LogoCarousel";
import Image from "next/image";

const HeroBanner = () => {
  const router = useRouter();

  return (
    <section className="container mt-16 flex flex-col-reverse md:flex-row ">
      <div className="my-24 flex flex-1 flex-col font-medium text-gray-950">
        <h1 className="my-10 text-6xl">
          Generate mesmerizing{" "}
          <span className="font-bold text-indigo-500">icons</span> with a click
          of a button
        </h1>
        <p className="text-xl font-normal text-gray-500">
          Unleash the Power of AI Creativity , with as little as 0.05$ per icon
        </p>
        <button onClick={() => router.push("/generate")} className="btn mt-8 ">
          Start for Free
        </button>
      </div>
      <div className="mt-8 flex-col md:block lg:block ">
        <Image
          src="/generatedicons.png"
          height={0}
          width={750}
          alt="generated ai icon"
        />
      </div>
    </section>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ai Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <HeroBanner />
        <h2 className="m-12 mx-auto text-center text-5xl">
          Generated by Icon AI Wizard
        </h2>
        <LogoCarousel className="m-16" />
      </main>
    </>
  );
};

export default Home;
