import { type NextPage } from "next";
import Head from "next/head";
import Spline from "@splinetool/react-spline";
import { useRouter } from "next/router";
import { Button } from "@nextui-org/react";

const HeroBanner = () => {
  const router = useRouter();

  return (
    <section className="container flex flex-col md:flex-row ">
      <div className="my-24 flex flex-1 flex-col font-medium text-gray-800">
        <h1 className="my-10 text-6xl">
          Generate awesome{" "}
          <span className="font-bold text-blue-700">icons</span> with a click of
          a button
        </h1>
        <p className="text-xl font-normal text-gray-500">
          Unleash the Power of AI Creativity , Try our AI generator today and
          see the possibilities!
        </p>
        <button onClick={() => router.push("/generate")} className="btn mt-8 ">
          Start for Free
        </button>
      </div>
      <div className="hidden h-screen w-[750px] lg:block ">
        <Spline scene="https://prod.spline.design/oc2DMbRI0LEgtP9D/scene.splinecode" />
      </div>
    </section>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ai Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <HeroBanner />
      </main>
    </>
  );
};

export default Home;
