name: Deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      HOST_NAME: ${{ secrets.HOST_NAME }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      PRICE_ID: ${{ secrets.PRICE_ID }}
      STRIPE_WEB_HOOK_SECRET: ${{ secrets.STRIPE_WEB_HOOK_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}
      MOCK_REPLICATE: ${{ secrets.MOCK_REPLICATE }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Deploy

        run: |
          npx prisma generate
          npx sst deploy --stage prod
